using Microsoft.EntityFrameworkCore;
using SolskaKnjiznica.Infrastructure.Persistence;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddDbContext<ApplicationDbContext>(options =>
    options.UseNpgsql(builder.Configuration.GetConnectionString("DefaultConnection")));

builder.Services.AddControllers();
// Learn more about configuring OpenAPI at https://aka.ms/aspnet/openapi
builder.Services.AddOpenApi();

builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowAll",
        builder => builder.AllowAnyOrigin()
                          .AllowAnyMethod()
                          .AllowAnyHeader());
});

var app = builder.Build();

// Create tables if they don't exist (using exact SQL schema provided by user)
using (var scope = app.Services.CreateScope())
{
    var dbContext = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
    // We use a simplified script that checks for table existence to avoid errors on reapplying
    await dbContext.Database.ExecuteSqlRawAsync("""
        CREATE TABLE IF NOT EXISTS uporabniki (
          id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          email character varying NOT NULL,
          geslo_hash character varying NOT NULL,
          ime character varying NOT NULL,
          priimek character varying NOT NULL,
          vloga character varying NOT NULL,
          ustvarjen_ob timestamp without time zone NOT NULL
        );

        CREATE TABLE IF NOT EXISTS jeziki (
          id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          ime character varying NOT NULL,
          kratica character varying NOT NULL
        );

        CREATE TABLE IF NOT EXISTS kategorije (
          id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          ime character varying NOT NULL
        );

        CREATE TABLE IF NOT EXISTS knjige (
          id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          naslov character varying NOT NULL,
          isbn character varying NOT NULL,
          leto integer NOT NULL,
          stevilo integer NOT NULL,
          slika_url character varying NOT NULL,
          jeziki_id integer NOT NULL,
          CONSTRAINT knjige_jeziki_id_fkey FOREIGN KEY (jeziki_id) REFERENCES jeziki(id)
        );

        CREATE TABLE IF NOT EXISTS avtorji (
          id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          ime character varying NOT NULL,
          priimek character varying NOT NULL
        );

        CREATE TABLE IF NOT EXISTS avtor_knjiga (
          id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          avtorji_id integer NOT NULL,
          knjige_id integer NOT NULL,
          CONSTRAINT avtor_knjiga_avtorji_id_fkey FOREIGN KEY (avtorji_id) REFERENCES avtorji(id),
          CONSTRAINT avtor_knjiga_knjige_id_fkey FOREIGN KEY (knjige_id) REFERENCES knjige(id)
        );

        CREATE TABLE IF NOT EXISTS dijaki (
          id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          ime character varying NOT NULL,
          priimek character varying NOT NULL,
          indetifikacijska_st character varying NOT NULL,
          email character varying NOT NULL
        );

        CREATE TABLE IF NOT EXISTS oprema (
          id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          ime character varying NOT NULL,
          serijska_st character varying NOT NULL,
          opis text NOT NULL,
          stevilo integer NOT NULL,
          slika_url character varying NOT NULL,
          kategorije_id integer NOT NULL,
          CONSTRAINT oprema_kategorije_id_fkey FOREIGN KEY (kategorije_id) REFERENCES kategorije(id)
        );

        CREATE TABLE IF NOT EXISTS izposoje (
          id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          datum_izposoje timestamp without time zone NOT NULL,
          datum_vrnitve timestamp without time zone,
          status character varying NOT NULL,
          poskodba_opis character varying NOT NULL,
          poskodba_slika_url character varying NOT NULL,
          knjige_id integer,
          dijaki_id integer NOT NULL,
          oprema_id integer,
          CONSTRAINT izposoje_uporabniki_fkey FOREIGN KEY (dijaki_id) REFERENCES uporabniki(id),
          CONSTRAINT izposoje_knjige_id_fkey FOREIGN KEY (knjige_id) REFERENCES knjige(id),
          CONSTRAINT izposoje_oprema_id_fkey FOREIGN KEY (oprema_id) REFERENCES oprema(id)
        );

        CREATE TABLE IF NOT EXISTS poskodbe (
          id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          datum timestamp without time zone NOT NULL,
          opis text NOT NULL,
          slika_url character varying,
          izposoje_id integer NOT NULL,
          dijaki_id integer,
          CONSTRAINT poskodbe_izposoje_id_fkey FOREIGN KEY (izposoje_id) REFERENCES izposoje(id),
          CONSTRAINT poskodbe_uporabniki_fkey FOREIGN KEY (dijaki_id) REFERENCES uporabniki(id)
        );

        CREATE TABLE IF NOT EXISTS rezervacije (
          id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          datum_rezervacije timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
          datum_od timestamp with time zone NOT NULL,
          datum_do timestamp with time zone NOT NULL,
          status text DEFAULT 'aktivna',
          knjige_id integer,
          oprema_id integer,
          dijaki_id integer,
          CONSTRAINT rezervacije_oprema_id_fkey FOREIGN KEY (oprema_id) REFERENCES oprema(id),
          CONSTRAINT rezervacije_dijaki_id_fkey FOREIGN KEY (dijaki_id) REFERENCES uporabniki(id),
          CONSTRAINT rezervacije_knjige_id_fkey FOREIGN KEY (knjige_id) REFERENCES knjige(id)
        );
        """);
}

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.MapOpenApi();
}

app.UseCors("AllowAll");
app.MapControllers();

app.MapGet("/health/db", async (IConfiguration config) =>
{
    try
    {
        var connStr = config.GetConnectionString("DefaultConnection");
        using var conn = new Npgsql.NpgsqlConnection(connStr);
        await conn.OpenAsync();
        return Results.Ok("Connected to Supabase");
    }
    catch (Exception ex)
    {
        return Results.Problem(detail: ex.ToString(), statusCode: 500);
    }
})
.WithName("HealthCheckDb");

app.Run();
